# Generated by Django 3.0.8 on 2020-08-03 21:07

from django.db import migrations, models
import django_countries.fields
import localflavor.generic.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('salutation', models.CharField(blank=True, choices=[('heer', 'Heer'), ('mevrouw', 'Mevrouw')], help_text='Aanhef, om eventueel te gebruiken bij automatische e-mails.', max_length=30)),
                ('street', models.CharField(blank=True, max_length=150)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('country', django_countries.fields.CountryField(blank=True, default='NL', max_length=2)),
                ('iban', localflavor.generic.models.IBANField(blank=True, include_countries=None, max_length=34, use_nordea_extensions=False, verbose_name='IBAN')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Yearly donation amount.', max_digits=8, null=True)),
                ('newsletter', models.BooleanField(help_text='Whether the donor wants to receive the newsletter.', null=True)),
            ],
        ),
    ]
