# Generated by Django 3.1.8 on 2021-04-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Yearly donation amount.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
