# Generated by Django 4.1.7 on 2023-03-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_auto_20210427_1318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
