services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/src
      - media:/app/media
    ports:
      - "8000:8000"
    environment:
      DJANGO_DEBUG: "on"
      DJANGO_SECRET_KEY: insecure
      DATABASE_URL: psql://postgres:postgres@db/postgres
      DJANGO_ALLOWED_HOSTS: "*"

  db:
    image: postgres:15
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  db:
  media:
