"""Production specific settings."""
from main.settings import *  # noqa: F403

DEBUG = False

# Secret key is randomly generated by the deploy script and put in this file
# See deployment/site.yml
with open('/app/tutti/secrets/secret_key.txt') as f:
    SECRET_KEY = f.read().strip()

# See secret key
with open('/app/tutti/secrets/postgres_pw.txt') as f:
    DATABASES['default'] = {  # noqa: F405
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'tutti',
        'USER': 'tutti',
        'PASSWORD': f.read().strip(),
        'CONN_MAX_AGE': 3600,
    }

# E-mail configuration
# Using the G Suite relay service we can send mails from @esmgquadrivium.nl.
# Authentication works via IP address, thus it only works on the production server.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.gmail.com'
EMAIL_USE_SSL = True
SERVER_EMAIL = 'info@esmgquadrivium.nl'
DEFAULT_FROM_EMAIL = 'info@esmgquadrivium.nl'
ADMINS = ['sysop@esmgquadrivium.nl']

ALLOWED_HOSTS = ['tutti.esmgquadrivium.nl']

STATIC_ROOT = '/app/tutti/static'
MEDIA_ROOT = '/app/tutti/media'

# HTTPS
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

SECURE_REFERRER_POLICY = 'no-referrer'
