# Generated by Django 3.0.8 on 2020-08-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0006_auto_20200820_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Closing date')),
                ('groups', models.ManyToManyField(blank=True, to='members.QGroup', verbose_name='Linked groups')),
                ('participants', models.ManyToManyField(blank=True, to='members.Person', verbose_name='Participants')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
            },
        ),
    ]
