# Generated by Django 3.0.8 on 2020-08-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200820_1918'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='date',
        ),
        migrations.AddField(
            model_name='activity',
            name='cost',
            field=models.CharField(default='n/a', max_length=150),
        ),
        migrations.AddField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='activity',
            name='hide_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='hide_participants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(default='n/a', max_length=150),
        ),
        migrations.AddField(
            model_name='activity',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owners', to='members.Person', verbose_name='Activity owners'),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='closing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closing date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, default='n/a'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activity',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='members.Person', verbose_name='Participants'),
        ),
    ]
