# Generated by Django 3.0.8 on 2020-08-25 13:39

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20200820_1918'),
        ('activities', '0002_auto_20200823_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'activities'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='closing_date',
            field=models.DateTimeField(blank=True, help_text="People can't sign up after this date.", null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Used for display only, can't be used to automatically debit people using Q-rekening (as of yet).", max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text="You can restrict sign up to people from certain groups. If you don't specify a group, all (current) members can sign up.", to='members.QGroup', verbose_name='linked groups'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='hide_participants',
            field=models.BooleanField(default=False, help_text='Participants will be hidden for everyone except the organizers.'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='activity',
            name='owners',
            field=models.ManyToManyField(blank=True, help_text='Organizers can modify the activity and get participant contact details.', related_name='activity_organized_set', to='members.Person', verbose_name='organizers'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='activity_set', to='members.Person'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(1234, 5, 6, 0, 0, tzinfo=timezone.utc)),
            preserve_default=False,
        ),
    ]
