# Generated by Django 3.0.8 on 2020-08-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20200825_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='closing_date',
            field=models.DateTimeField(blank=True, help_text='Time and date enlisting closes.', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='cost',
            field=models.CharField(blank=True, default='', help_text='Used for display only.', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='End time and date of the activity.', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(help_text='Start time and date of the activity.'),
        ),
    ]
