# Generated by Django 2.2.5 on 2020-03-09 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qluis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='membership_end',
        ),
        migrations.RemoveField(
            model_name='person',
            name='membership_start',
        ),
        migrations.AlterField(
            model_name='membership',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='iban',
            field=models.CharField(blank=True, max_length=150, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='person',
            name='keywatcher_id',
            field=models.CharField(blank=True, max_length=4, verbose_name='KeyWatcher ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='keywatcher_pin',
            field=models.CharField(blank=True, max_length=4, verbose_name='KeyWatcher PIN'),
        ),
    ]
