# Generated by Django 2.2.5 on 2019-09-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qluis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='name'),
            preserve_default=False,
        ),
    ]
