# Generated by Django 2.2.5 on 2020-03-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qluis', '0002_auto_20200309_1908'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(end=None), fields=('group', 'person'), name='unique_memberships'),
        ),
    ]
