# Generated by Django 3.0.4 on 2020-03-11 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qluis', '0002_auto_20200312_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcardloan',
            name='deposit_made',
            field=models.CharField(blank=True, choices=[('nn', 'No'), ('n', 'Probably not'), ('y', 'Probably yes'), ('yy', 'Most definitely')], help_text='Money deposit for the card.', max_length=4),
        ),
        migrations.AlterField(
            model_name='externalcardloan',
            name='end',
            field=models.DateField(blank=True, help_text='If empty, the person is currently borrowing the card.', null=True),
        ),
        migrations.AlterField(
            model_name='externalcardloan',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
