# Generated by Django 3.0.4 on 2020-03-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qluis', '0003_auto_20200312_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcardloan',
            name='deposit_made',
            field=models.CharField(blank=True, choices=[('n', 'No'), ('n?', 'Probably not'), ('y?', 'Probably yes'), ('y', 'Most definitely')], help_text='Money deposit for the card.', max_length=4),
        ),
        migrations.AlterField(
            model_name='gsuiteaccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='keywatcher_id',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='KeyWatcher ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='keywatcher_pin',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='KeyWatcher PIN'),
            preserve_default=False,
        ),
    ]
