# Generated by Django 2.2.5 on 2019-09-29 02:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('qluis', '0003_auto_20190927_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.CharField(blank=True, help_text='Additional indication that is written on the card.', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='GSuiteAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('room_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='created_by',
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='group',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='bhv_certificate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='external_card_deposit_made',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='person',
            name='found_via',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='iban',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='person',
            name='initials',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='is_student',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='keywatcher_id',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='person',
            name='keywatcher_pin',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='person',
            name='membership_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='membership_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='permission_exquus',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='person_id',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='person',
            name='postal_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('nl-nl', 'Dutch')], max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='sepa_direct_debit',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='street',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='person',
            name='tue_card_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='external_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='qluis.ExternalCard'),
        ),
        migrations.AddField(
            model_name='person',
            name='gsuite_accounts',
            field=models.ManyToManyField(blank=True, to='qluis.GSuiteAccount'),
        ),
        migrations.AddField(
            model_name='person',
            name='instruments',
            field=models.ManyToManyField(blank=True, to='qluis.Instrument'),
        ),
        migrations.AddField(
            model_name='person',
            name='key_access',
            field=models.ManyToManyField(blank=True, to='qluis.Key'),
        ),
    ]
