# Generated by Django 2.2.5 on 2020-03-11 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qluis', '0003_auto_20200309_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='groups',
        ),
        migrations.AlterField(
            model_name='externalcard',
            name='card_number',
            field=models.IntegerField(help_text='7-digit (usually) card identifier number.', null=True),
        ),
        migrations.AlterField(
            model_name='externalcard',
            name='reference_number',
            field=models.IntegerField(blank=True, help_text='Short reference number written on the card.', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='bhv_certificate',
            field=models.DateField(blank=True, null=True, verbose_name='BHV certificate date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='person ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sepa_direct_debit',
            field=models.BooleanField(blank=True, null=True, verbose_name='SEPA direct debit'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tue_card_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='TU/e card number'),
        ),
        migrations.CreateModel(
            name='ExternalCardLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(blank=True, help_text='If empty, the person is currently borrowing the card.', null=True)),
                ('deposit_made', models.CharField(blank=True, choices=[('nn', 'No'), ('n', 'Probably not'), ('y', 'Probably yes'), ('yy', 'Most definitely')], max_length=4)),
                ('external_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qluis.ExternalCard')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qluis.Person')),
            ],
        ),
    ]
