# Generated by Django 3.0.4 on 2020-03-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qluis', '0004_auto_20200314_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='qgroup',
            name='end_on_unsubscribe',
            field=models.BooleanField(default=True),
        ),
    ]
