# Generated by Django 2.2.5 on 2019-09-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qluis', '0007_auto_20190929_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalcard',
            name='card_number',
            field=models.IntegerField(null=True),
        ),
    ]
