# Generated by Django 2.2.6 on 2020-01-15 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qluis', '0008_auto_20190929_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='room_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='person',
            name='external_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='qluis.ExternalCard'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(auto_now_add=True, verbose_name='Start date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qluis.Group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qluis.Person')),
            ],
        ),
    ]
