# Generated by Django 2.2.5 on 2020-03-08 22:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qluis', '0009_auto_20200115_0956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='QGroup',
        ),
        migrations.RemoveField(
            model_name='person',
            name='found_via',
        ),
        migrations.RemoveField(
            model_name='person',
            name='permission_exquus',
        ),
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qluis.Group'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qluis.Person'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bhv_certificate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='external_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qluis.ExternalCard'),
        ),
        migrations.AlterField(
            model_name='person',
            name='external_card_deposit_made',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', through='qluis.Membership', to='qluis.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_student',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='membership_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='membership_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='sepa_direct_debit',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='tue_card_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
