# Generated by Django 2.2.6 on 2020-02-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qrekening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtors', models.FileField(upload_to='qrekening')),
                ('creditors', models.FileField(upload_to='qrekening')),
            ],
        ),
    ]
