# Generated by Django 2.2.6 on 2020-02-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pennotools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrekening',
            name='creditors',
        ),
    ]
