# Generated by Django 2.2.6 on 2020-02-27 19:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pennotools', '0002_remove_qrekening_creditors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrekening',
            name='debtors',
        ),
        migrations.AddField(
            model_name='qrekening',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrekening',
            name='due',
            field=models.DateField(default=datetime.datetime(2020, 3, 12, 20, 42, 45, 669020)),
        ),
        migrations.CreateModel(
            name='DavilexData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('debtor', 'Debtors'), ('creditor', 'Creditors')], max_length=20)),
                ('file', models.FileField(upload_to='qrekening')),
                ('qrekening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pennotools.Qrekening')),
            ],
        ),
    ]
