# Generated by Django 2.2.6 on 2020-02-27 20:08

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pennotools', '0003_auto_20200227_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrekening',
            name='qrekening',
            field=models.FileField(default=django.utils.timezone.now, editable=False, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrekening',
            name='due',
            field=models.DateField(default=datetime.datetime(2020, 3, 12, 21, 7, 44, 856151)),
        ),
    ]
