# Generated by Django 2.2.5 on 2020-03-08 22:54

from django.db import migrations
import ldapsync.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qluis', '0010_auto_20200308_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ldapsync.models.LDAPMixin, 'qluis.qgroup'),
        ),
        migrations.CreateModel(
            name='LDAPPerson',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ldapsync.models.LDAPMixin, 'qluis.person'),
        ),
    ]
