# Generated by Django 3.0.4 on 2020-03-17 16:36

from django.db import migrations
import ldapsync.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ldapsync.models.LDAPMixin, 'members.qgroup'),
        ),
        migrations.CreateModel(
            name='LDAPPerson',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ldapsync.models.LDAPMixin, 'members.person'),
        ),
    ]
