# Generated by Django 2.2.5 on 2019-09-20 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LdapEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dn', models.CharField(max_length=255)),
                ('key_value', models.IntegerField(db_column='keyval')),
            ],
            options={
                'db_table': 'ldap_entries',
            },
        ),
        migrations.CreateModel(
            name='ObjectClassMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('key_table', models.CharField(db_column='keytbl', max_length=64)),
                ('key_column', models.CharField(db_column='keycol', max_length=64)),
            ],
            options={
                'db_table': 'ldap_oc_mappings',
            },
        ),
        migrations.CreateModel(
            name='LdapEntryObjectClasses',
            fields=[
                ('entry_id', models.ForeignKey(db_column='entry_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ldapproxy.LdapEntry')),
                ('object_class_name', models.CharField(db_column='oc_name', max_length=64)),
            ],
            options={
                'db_table': 'ldap_entry_objclasses',
            },
        ),
        migrations.AddField(
            model_name='ldapentry',
            name='object_class_mapping',
            field=models.ForeignKey(db_column='oc_map_id', on_delete=django.db.models.deletion.CASCADE, to='ldapproxy.ObjectClassMapping'),
        ),
        migrations.AddField(
            model_name='ldapentry',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ldapproxy.LdapEntry'),
        ),
        migrations.CreateModel(
            name='AttributeMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('select_expression', models.CharField(db_column='sel_expr', max_length=255)),
                ('from_tables', models.CharField(db_column='from_tbls', max_length=255)),
                ('join_where', models.CharField(max_length=255, null=True)),
                ('object_class_mapping', models.ForeignKey(db_column='oc_map_id', on_delete=django.db.models.deletion.CASCADE, to='ldapproxy.ObjectClassMapping')),
            ],
            options={
                'db_table': 'ldap_attr_mappings',
            },
        ),
    ]
