# Generated by Django 2.2.5 on 2019-09-20 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldapproxy', '0003_ldap_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapentry',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ldapproxy.LdapEntry'),
        ),
    ]
