# Generated by Django 3.0.4 on 2020-03-19 16:52

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import localflavor.generic.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ExternalCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(blank=True, help_text='7-digit (usually) card identifier number.', null=True)),
                ('reference_number', models.IntegerField(blank=True, help_text='Short reference number written on the card.', null=True)),
                ('description', models.CharField(blank=True, help_text='Additional indication that is written on the card.', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='GSuiteAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'G Suite account',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('initials', models.CharField(blank=True, max_length=30)),
                ('street', models.CharField(blank=True, max_length=150)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('country', django_countries.fields.CountryField(blank=True, default='NL', max_length=2)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('preferred_language', models.CharField(blank=True, choices=[('en-us', 'English'), ('nl-nl', 'Dutch')], max_length=30)),
                ('tue_card_number', models.IntegerField(blank=True, null=True, verbose_name='TU/e card number')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=30)),
                ('is_student', models.BooleanField(blank=True, null=True)),
                ('sepa_direct_debit', models.BooleanField(blank=True, null=True, verbose_name='SEPA direct debit')),
                ('bhv_certificate', models.DateField(blank=True, null=True, verbose_name='BHV certificate date')),
                ('field_of_study', models.CharField(blank=True, max_length=150)),
                ('iban', localflavor.generic.models.IBANField(blank=True, include_countries=None, max_length=34, use_nordea_extensions=False, verbose_name='IBAN')),
                ('person_id', models.CharField(blank=True, max_length=30, verbose_name='person ID')),
                ('keywatcher_id', models.CharField(blank=True, max_length=4, verbose_name='KeyWatcher ID')),
                ('keywatcher_pin', models.CharField(blank=True, max_length=4, verbose_name='KeyWatcher PIN')),
                ('notes', models.TextField(blank=True)),
                ('gsuite_accounts', models.ManyToManyField(blank=True, to='members.GSuiteAccount', verbose_name='G Suite accounts')),
                ('instruments', models.ManyToManyField(blank=True, to='members.Instrument')),
                ('key_access', models.ManyToManyField(blank=True, to='members.Key')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
            },
            bases=('members.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end date')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='person')),
            ],
        ),
        migrations.CreateModel(
            name='QGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('end_on_unsubscribe', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(blank=True, help_text='E.g. the commissioner.', null=True, on_delete=django.db.models.deletion.PROTECT, to='members.Person')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='ExternalCardLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(default=django.utils.timezone.now)),
                ('end', models.DateField(blank=True, help_text='If empty, the person is currently borrowing the card.', null=True)),
                ('deposit_made', models.CharField(blank=True, choices=[('n', 'No'), ('n?', 'Probably not'), ('y?', 'Probably yes'), ('y', 'Most definitely')], help_text='Money deposit for the card.', max_length=4)),
                ('external_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.ExternalCard')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Person')),
            ],
        ),
    ]
