# Generated by Django 3.0.5 on 2020-05-04 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': [('change_treasurer_fields', 'Can change treasurer related fields')], 'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_id',
            field=models.CharField(blank=True, help_text='Davilex code.', max_length=30, verbose_name='person ID'),
        ),
        migrations.AlterField(
            model_name='qgroup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='qgroup',
            name='end_on_unsubscribe',
            field=models.BooleanField(default=True, help_text='If set, when a person is unsubscribed she is removed from this group.'),
        ),
    ]
