# Generated by Django 3.0.8 on 2020-08-03 14:32

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20200504_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonTreasurerFields',
            fields=[
            ],
            options={
                'verbose_name_plural': 'people treasurer fields',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('members.person',),
            managers=[
                ('objects', members.models.PersonManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('objects', members.models.PersonManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='qgroup',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='ldap_password',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='qgroup',
            name='end_on_unsubscribe',
            field=models.BooleanField(default=True, help_text='If set, when a person is unsubscribed they are removed from this group.'),
        ),
    ]
