# Generated by Django 3.0.8 on 2020-08-17 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200803_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='qgroup',
            name='category',
            field=models.CharField(blank=True, choices=[('committee', 'Committee'), ('ensemble', 'Ensemble'), ('subassociation', 'Sub-association')], db_index=True, help_text="Leave empty when there's no applicable option.", max_length=30),
        ),
        migrations.AddField(
            model_name='qgroup',
            name='show_in_overview',
            field=models.BooleanField(default=True, help_text='Whether the group is visible in the groups overview, with group members.'),
        ),
        migrations.AlterField(
            model_name='qgroup',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='E.g. the commissioner. Currently not used for anything.', null=True, on_delete=django.db.models.deletion.PROTECT, to='members.Person'),
        ),
    ]
