# Generated by Django 3.0.8 on 2020-08-18 09:38

from django.db import migrations, models
import django_countries.fields
import localflavor.generic.models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20200803_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('instruments', models.CharField(max_length=150, verbose_name='instrument(s)')),
                ('initials', models.CharField(blank=True, max_length=30)),
                ('street', models.CharField(blank=True, max_length=150)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('country', django_countries.fields.CountryField(blank=True, default='NL', max_length=2)),
                ('preferred_language', models.CharField(blank=True, choices=[('en-us', 'English'), ('nl-nl', 'Dutch')], max_length=30)),
                ('tue_card_number', models.IntegerField(blank=True, null=True, verbose_name='TU/e card number')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=30)),
                ('is_student', models.BooleanField(blank=True, null=True)),
                ('sub_association', multiselectfield.db.fields.MultiSelectField(choices=[('ensuite', 'Ensuite - symphony orchestra'), ('vokollage', 'Vokollage - choir'), ('auletes', 'Auletes - wind orchestra'), ('piano', 'Piano member - use our rehearsal rooms and join association-wide activities')], help_text='Which sub-associations are you interested in? If you are not interested in the orchestra and choir, select piano member.', max_length=31)),
                ('field_of_study', models.CharField(blank=True, max_length=150)),
                ('iban', localflavor.generic.models.IBANField(blank=True, include_countries=None, max_length=34, use_nordea_extensions=False, verbose_name='IBAN')),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
