# Generated by Django 3.0.8 on 2020-08-18 10:36

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_membershiprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprequest',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the form was submitted.'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='sub_association',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ensuite', 'Ensuite - symphony orchestra'), ('vokollage', 'Vokollage - choir'), ('auletes', 'Auletes - wind orchestra'), ('piano', 'Piano member - use our rehearsal rooms and join association-wide activities')], help_text='Which sub-associations are you interested in? If you are not interested in the orchestra and choir, select piano member.', max_length=31, verbose_name='sub-association'),
        ),
    ]
