# Generated by Django 3.0.8 on 2020-08-20 14:35

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200818_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='key',
            options={'ordering': ('number',)},
        ),
        migrations.AddField(
            model_name='qgroup',
            name='category',
            field=models.CharField(blank=True, choices=[('committee', 'Committee'), ('ensemble', 'Ensemble'), ('subassociation', 'Sub-association')], db_index=True, help_text="Leave empty when there's no applicable option.", max_length=30),
        ),
        migrations.AddField(
            model_name='qgroup',
            name='show_in_overview',
            field=models.BooleanField(default=True, help_text='Whether the group is visible in the groups overview, with group members.'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='email',
            field=models.EmailField(max_length=150, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='instruments',
            field=models.CharField(max_length=150, verbose_name='instrument(s) or voice'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='is_student',
            field=models.BooleanField(blank=True, null=True, verbose_name='student'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='street',
            field=models.CharField(blank=True, max_length=150, verbose_name='street and house number'),
        ),
        migrations.AlterField(
            model_name='membershiprequest',
            name='sub_association',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('vokollage', 'Vokollage – choir'), ('ensuite', 'Ensuite – symphony orchestra'), ('auletes', 'Auletes – wind orchestra'), ('piano', 'Piano member – join association-wide activities and use our rehearsal rooms')], max_length=31, verbose_name='sub-association'),
        ),
        migrations.AlterField(
            model_name='qgroup',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='E.g. the commissioner. Currently not used for anything.', null=True, on_delete=django.db.models.deletion.PROTECT, to='members.Person'),
        ),
    ]
