# Generated by Django 3.0.8 on 2020-09-11 19:52
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Person = apps.get_model('members', 'Person')
    for row in Person.objects.all():
        row.azure_immutable_id = str(uuid.uuid4())
        row.save(update_fields=['azure_immutable_id'])


class Migration(migrations.Migration):
    dependencies = [
        ('members', '0007_person_azure_id_1'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop, elidable=True)
    ]
