# Generated by Django 3.1.8 on 2021-12-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20210427_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sepa_sign_date',
            field=models.DateField(blank=True, null=True, verbose_name='SEPA agreement date'),
        ),
    ]
