# Generated by Django 4.1 on 2022-08-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_person_sepa_sign_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershiprequest',
            name='sub_association',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gsuite_accounts',
        ),
        migrations.DeleteModel(
            name='GSuiteAccount',
        ),
    ]
