# Generated by Django 4.2.13 on 2024-05-12 18:38

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_remove_membershiprequest_sub_association_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo_video_consent_external',
            field=models.BooleanField(blank=True, help_text='Whether the person has given consent to share photos and videos of them externally (on website, social media).', null=True, verbose_name='photos/videos share consent external'),
        ),
        migrations.AddField(
            model_name='person',
            name='photo_video_consent_internal',
            field=models.BooleanField(blank=True, help_text='Whether the person has given consent to share photos and videos of them internally with other members.', null=True, verbose_name='photos/videos share consent between members'),
        ),
    ]
