# Generated by Django 6.1.1 on 2026-09-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_rename_seen_membershiprequest_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='conscribo_relation_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='Conscribo relation number'),
        ),
    ]
