# Generated by Django 2.2.5 on 2019-09-20 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldapproxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapentryobjectclasses',
            name='entry_id',
            field=models.OneToOneField(db_column='entry_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ldapproxy.LdapEntry'),
        ),
    ]
