name: Continuous integration

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          dev-requirements.txt
    - name: Install dependencies
      # About --use-pep517: https://github.com/pypa/pip/issues/8559
      run: pip install --use-pep517 -r requirements.txt -r dev-requirements.txt
    - name: Run tests
      run: python manage.py test
      env:
        DJANGO_SECRET_KEY: insecure
        DJANGO_DEBUG: on
    - name: Lint with flake8
      run: flake8
